apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: url-shortner             
spec:
  replicas: 2                    
  selector:
    matchLabels:
      app: url-shortner
  template:                      
    metadata:
      labels:                    
        app: url-shortner 
    spec:
      containers:
      - name: url-shortner
        image: akankshakumari393/url-shortner
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8080      
        env:                     
          - name: REDIS_HOST
            value: redis-master
          - name: REDIS_PORT
            value: "6379"

---
apiVersion: v1
kind: Service                    
metadata:
  name: url-shortner-service     
spec:
  type: NodePort         
  ports:                         
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: url-shortner     